"use strict";this.default_GameCenterUi=this.default_GameCenterUi||{};(function(_){var window=this;
try{
_.wg(_.rt);
_.q("sOXFj");
var gA=function(a){_.Q.call(this,a.na)};_.H(gA,_.Q);gA.ta=_.Q.ta;gA.ha=_.Q.ha;gA.prototype.j=function(a){return a()};_.R(_.qt,gA);
_.r();
_.q("oGtAuc");
_.Pfa=new _.ne(_.rt);
_.r();
_.eB=function(a){_.Mp.call(this,a.na);this.soy=this.Ud=null;if(this.Xd()){var b=_.un(this.Gc(),[_.mo,_.km]);b=_.Ff([b[_.mo],b[_.km]]).then(function(c){this.soy=c[0];this.Ud=c[1]},null,this);_.Np(this,b)}this.O=a.hd.OD};_.H(_.eB,_.Mp);_.eB.ha=function(){return{hd:{OD:function(){return _.cg(this)}}}};_.eB.prototype.getContext=function(a){return this.O.getContext(a)};_.eB.prototype.getData=function(a){return this.O.getData(a)};_.eB.prototype.Yo=function(){};
_.fB=function(a,b){_.Op(b);a&&_.pe.ab().register(a,b)};
_.q("q0xTif");
var iga=function(a){var b=function(d){_.Jq(d)&&(_.Jq(d).Wa=null,_.HA(d,null));d.XyHi9&&(d.XyHi9=null)};b(a);a=a.querySelectorAll("[c-wiz]");for(var c=0;c<a.length;c++)b(a[c])};_.hB=function(a){_.eB.call(this,a.na);var b=this,c=a.context.KD;this.j=c.Kf;this.N=this.T=this.o=null;this.v=a.service.Va;this.U=a.service.kJ;a=this.j.O.then(function(d){b.o=d;d=b.j.id.yy(d,b.j.j);b.T=d.variant});c=c.rv.then(function(d){b.N=d});this.wr=this.wr.bind(this);_.Np(this,_.Ff([a,c]))};_.H(_.hB,_.eB);_.hB.ha=function(){return{context:{KD:"FVxLkf"},service:{Va:_.eA,component:_.TA,kJ:_.Pfa}}};_.k=_.hB.prototype;_.k.Cr=function(){return""};_.k.Cp=function(){return!1};_.k.Je=function(){return this.j};
_.k.uk=function(){var a=_.kb(this.N,this.wr);a={Lf:this.j.j,Hq:this.j.T,Mi:{II:!1,Lf:this.j.j,On:this.j.id.N,Yw:this.j.sm,Fm:this.Cr(),jsdata:_.lb(this.o)},TM:a,BM:this.T};Object.assign(a,this.o||{});Object.assign(a,this.j.o);Object.assign(a.Mi,this.j.o);return a};_.k.wr=function(a,b){return Array.isArray(a)?1!=a.length||(b=this.j.id.Xp()[b],b&&b.Dx)?_.xe(a,function(c){return c.uk()}):a[0].uk():a.uk()};_.k.Ll=function(){return null};
var iB=function(a){var b=a.Ir();return function(){var c=_.Fb.apply(0,arguments);return a.U.j(function(){return b.apply(null,_.fg(c))})}},jga=function(a){var b=a.Ll();return b?function(){var c=_.Fb.apply(0,arguments);return a.U.j(function(){return b.apply(null,_.fg(c))})}:b};_.hB.prototype.dw=function(){return!1};
_.hB.prototype.render=function(){var a=this.uk(),b=iB(this);b=this.Cp()?kga(this,b,a):this.soy.ac(b,a);this.Ll()&&(a=jB(this,a),b.appendChild(a));(a=this.j.id.Gr())&&0<a.length&&a.forEach(function(){});this.j.Fd(b);return b};
var jB=function(a,b){var c=a.Ud.j.j.createElement("view-header");c.style.display="none";var d=jga(a);b=a.dw()?b:{Lf:a.j.j};a.Cp()?a.v.tj(c,d,b):(a=a.soy.YH(d,b),c.appendChild(a));return c},kga=function(a,b,c){var d=a.Ud.j.j.createElement("div");a.v.tj(d,b,c);return 1==d.childNodes.length?d.firstChild:d};_.hB.prototype.Yo=function(a){var b=this.uk(),c=iB(this);iga(a);this.v.qe(a,c,b);this.Je().Fd(a);this.Ll()&&(b=jB(this,b),b=(new _.P(b)).Qb(),_.Zf(_.Ni(a).body,_.gB,b))};_.fB(_.dB,_.hB);
_.r();
var a4,bta,cta,dta;a4=function(){return _.mQ("")?"":void 0};bta=0;cta=function(){return _.Fb.apply(0,arguments).filter(function(a){return _.W(a)}).join(";")};_.b4=function(a){var b=_.Fb.apply(1,arguments);return(b="class"===a?_.EI.apply(null,_.fg(b)):cta.apply(null,_.fg(b)))?(0,_.sI)(a+'="'+b+'"'):(0,_.sI)("")};dta=/^[a-zA-Z0-9+\/_-]+={0,2}$/;var c4;_.d4=function(a,b,c,d){d=void 0===d?"":d;a.open("div","V2kJQb");a.va(c4||(c4=["jsaction","rcuQ6b:npT2md"]));a.W("jscontroller","BMRYDe");a.W("data-title",b);a.W("data-app-key",c);a.W("data-game-id",d);a.qa();a.Ya()};var e4;var eta=function(a,b){var c=b.body,d=b.class,e=b.Na,f=b.jslog,g=b.attributes,h=b.jscontroller,l=b.jsmodel,m=b.jsaction,p=b.jsname,t=b.SG,u=b.QG,v=b.MD,z=b.Mi,A=b.Lf,F=b.tE,X=b.kr,D="";D+=""+(null!=e?e:"");D+=v?" Ubi8Z":"";var aa=D+=u?" rETSD":"";e="c"+_.jP++;a.open("c-wiz","pdLipf");a.va(f4||(f4=["c-wiz",""]));_.mQ(null==z?void 0:z.Fm)&&a.W("jsrenderer",""+z.Fm);_.kQ(a,_.$P(_.b4("class",d,aa)));null!=f&&a.W("jslog",f);_.mQ(g)&&_.kQ(a,_.$P(g));t||a.W("jsshadow","");a.W("jsdata","deferred-"+e);if((F||
!_.mQ(null==z?void 0:z.II))&&(_.mQ(null==z?void 0:z.Lf)||_.mQ(A))){var cb;a.W("data-p","%.@."+(null!=(cb=null==z?void 0:z.Lf)?cb:null!=A?A:null).re().substr(1))}null!=h&&a.W("jscontroller",h);m&&a.W("jsaction",m);null!=p&&a.W("jsname",p);_.mQ(null==z?void 0:z.Yw)&&a.W("data-node-index",""+z.Yw);_.mQ(null==z?void 0:z.On)&&a.W("autoupdate","");a.W("jsmodel","hc6Ubd"+(l?" "+l:""));_.mQ(null==z?void 0:z.eO)&&a.W("view","");null!=X&&_.kQ(a,_.$P(X));a.qa();a.print(c);b=_.uI({Mi:z},b);c=b.Mi;b=b.jsdata;
g="";if(_.mQ(null==c?void 0:c.jsdata))for(c=c.jsdata,d=c.length,f=0;f<d;f++)h=c[f],_.mQ(h)?(h?(l="$"+bta++,l=(h.yb?_.Lw(h).Pf:";unsupported")+";"+l,_.Vy[l]||_.Wy++,_.Vy[l]=h,h=l):h="",h=" "+h):h="",g+=h;b=g+(b?" "+b:"");a.open("c-data","YoOZ2e");a.W("id",e);b&&a.W("jsdata",b);a.qa();a.close();a.Ya()},f4;var g4,h4,i4,j4,k4;
_.l4=function(a,b,c,d,e){var f=a.FD,g="",h=g+="SSPGKf",l=_.mQ()&&!f;f=_.hQ(function(p){l&&(p.open("div","iFmvKe"),p.va(g4||(g4=["jsname","NsVJLb","class","QMEh5b"])),p.qa(),p.open("div","JxQQcd"),p.va(h4||(h4=["jsname","tJHJj","class","AOq4tb"])),p.qa(),p.print(void 0),p.close(),p.close());_.mQ()&&p.print(void 0);if(_.mQ()||l){p.Ea("x2sfgd");var t=a&&a.TD,u="";p.open("script","x6fO0b");p.va(e4||(e4=["aria-hidden","true"]));if(t){var v=p.W;t=String(t);t=dta.test(t)?t:"zSoyz";v.call(p,"nonce",t)}p.qa();
u+="window.wiz_progress&&window.wiz_progress();";p.Oi()&&(p.Oi().textContent=_.Eb(_.Db((0,_.xia)(u).toString())));p.yp();p.Ya();p.Fa()}p.open("div","Bx1yje");p.va(i4||(i4=["jsname","a9kxte"]));u=p.W;v=_.dQ("e")(null,a);u.call(p,"class","T4LgNb "+v);p.qa();p.open("div","iLT7Ic");p.va(j4||(j4=["jsname","qJTHM","class","kFwPee"]));p.qa();l&&(p.open("div","Iwkcbc"),p.va(k4||(k4=["class","ydMMEb"])),p.qa(),p.close());p.print(c);p.close();p.close()});var m=_.jQ(function(p){p.W("data-ogpc","");_.mQ()&&_.kQ(p,
_.$P());_.mQ(d)&&_.mQ(d.hidden)&&p.W("style","display: none; visibility: hidden; opacity: 0;")});eta(b,{Lf:e,Mi:d,jsdata:void 0,jsmodel:void 0,SG:!0,QG:!1,MD:!1,tE:void 0,body:f,class:_.EI(void 0,h),jslog:a4(),jscontroller:a4(),jsaction:a4(),jsname:a4(),kr:m})};_.cQ("e",0,function(){return"eejsDc"});
_.cQ("e",1,function(){return""});
_.q("EtQCnc");
var C5=function(a){this.ya=_.x(a)};_.H(C5,_.C);C5.prototype.Qb=function(){return _.Yk(this,2,"High Score")};C5.prototype.wc=function(a){_.dl(this,2,a)};C5.prototype.Vs=function(a){_.dl(this,4,a)};var D5=function(a){return _.yD(a,C5,4)},E5=function(){_.ZP.call(this)};_.H(E5,_.ZP);_.k=E5.prototype;_.k.Hb=function(){return this.data.ariaLabel};_.k.kd=function(){return this.data.attributes};_.k.zC=function(){var a=this.data.Bd;return void 0===a?!1:a};
_.k.Xa=function(){var a=this.data.disabled;return void 0===a?!1:a};_.k.iw=function(){var a=this.data.uc;return void 0===a?!1:a};
var F5,G5,wta=function(a,b){var c=b.jscontroller,d=b.xk,e=b.yk,f=b.LF,g=b.Ch,h=b.bi,l=b.ix,m=b.bx,p=b.ariaLabel,t=b.kD,u=b.jD,v=b.Na,z=b.jsname,A=b.attributes,F=b.Bd;F=void 0===F?!1:F;var X=b.disabled;X=void 0===X?!1:X;var D=b.fh;D=void 0===D?!1:D;b=b.uc;b=void 0===b?!1:b;a.open("button","DsOYUd");a.W("class",_.EI(d,v));a.W("jscontroller",c);a.W("jsaction",_.J1(D)+"focus:h06R8; blur:zjh6rb;mlnRJb:fLiPzd;");v&&a.W("data-idom-class",v);z&&a.W("jsname",z);X&&a.W("disabled","");t&&u?(a.W("aria-label",
F?t:u),a.W("data-aria-label-on",t),a.W("data-aria-label-off",u)):p&&(a.W("aria-label",p),a.W("aria-pressed",""+F));b&&_.KQ(a);_.kQ(a,_.$P(null!=A?A:""));a.qa();a.Ea("B0p92");_.K1(a,g);a.Fa();a.Ea("KOVtEd");_.M1(a);a.Fa();a.open("span","moEyy");a.va(F5||(F5=["jsname","Hjh9Ae","aria-hidden","true"]));a.W("class","material-icons-extended "+f);a.qa();a.print(l);a.close();a.open("span","Yi7GCf");a.va(G5||(G5=["jsname","S5tZuc","aria-hidden","true"]));a.W("class","material-icons-extended "+e);a.qa();a.print(m);
a.close();a.open("div","MGiUbe");a.W("class",h);a.qa();a.close();a.Ya()},H5=function(){_.ZP.call(this)};_.H(H5,_.ZP);H5.prototype.Hb=function(){return this.data.ariaLabel};H5.prototype.kd=function(){return this.data.attributes};
var I5,J5,xta=function(a,b){var c=b.jscontroller,d=b.xk,e=b.yk,f=b.Ch,g=b.Oo,h=b.icon,l=b.ariaLabel,m=b.Na,p=b.jsname,t=b.attributes,u=b.kj,v=b.Bk;b=b.No;a.open("div","o9Wkjc");a.W("class",_.EI(d,m));a.W("jscontroller",c);a.W("jsaction",_.J1()+"focus:h06R8; blur:zjh6rb;mlnRJb:fLiPzd;");m&&a.W("data-idom-class",m);p&&a.W("jsname",p);_.kQ(a,_.$P(null!=t?t:""));a.qa();a.Ea("vbAlre");_.M1(a);a.Fa();a.open("span","tgzVke");a.va(I5||(I5=["jsname","S5tZuc","aria-hidden","true"]));a.W("class",e);a.qa();a.print(null!=
h?h:"");a.close();a.open("a","LoUt8b");a.va(J5||(J5=["jsname","hSRGPd"]));a.W("class",g);null!=u&&a.W("href",_.CI(u));v&&a.W("target",v);a.W("aria-label",l);null!=b&&_.kQ(a,_.$P(b));a.qa();a.close();a.Ea("bGXN7e");_.K1(a,f);a.Fa();a.Ya()},yta=function(a,b,c){var d=(0,_.rI)("#"),e=_.jQ(function(f){_.kQ(f,_.$P(""))});b.print(_.hQ(function(f){f.Ea("kdVdx");var g={jscontroller:"EKHvcb",xk:_.EI("pYTkkf-Bz112c-LgbsSe",void 0,!1),yk:"pYTkkf-Bz112c-kBDsod-Rtc0Jf",Ch:"pYTkkf-Bz112c-UHGRz",Oo:_.EI("pYTkkf-Bz112c-mRLv6",
"pYTkkf-Bz112c-RLmnJb"),ariaLabel:"Go Home",Na:"pNR8Uc",icon:c,kj:d,Bk:void 0,No:void 0,jk:!1,jsname:"Bki2je",attributes:e};f.Ac(H5,"o9Wkjc","div",g,a,xta);f.Fa()}))},zta=function(a,b,c){var d=void 0===d?!1:d;var e=_.jQ(function(g){_.kQ(g,_.$P(""))}),f=_.hQ(function(g){g.Ea("N2yT4d");_.O1(g,{jscontroller:"O626Fe",vl:_.EI("mUIrbf-LgbsSe",(_.mQ(),_.mQ()?"mUIrbf-LgbsSe-OWXEXe-Bz112c-M1Soyc":!1),_.mQ()&&void 0,!1,d&&"mUIrbf-LgbsSe-OWXEXe-zcdHbf","mUIrbf-LgbsSe-OWXEXe-dgl2Hf"),mm:_.EI("mUIrbf-kBDsod-Rtc0Jf",
"mUIrbf-kBDsod-Rtc0Jf-OWXEXe-M1Soyc"),an:_.EI("mUIrbf-kBDsod-Rtc0Jf","mUIrbf-kBDsod-Rtc0Jf-OWXEXe-UbuQg"),km:"mUIrbf-vQzf8d",bi:"mUIrbf-RLmnJb",label:c,ariaLabel:void 0,iD:void 0,Na:"oJ0sIe",disabled:void 0,icon:void 0,jk:void 0,hj:void 0,Yb:!1,jsname:"AHldd",fh:void 0,ci:3,attributes:e},a);g.Fa()});b.print(_.hQ(function(g){g.print(f)}))},Ata=function(a,b,c,d,e,f){var g=void 0===e?!1:e;var h=void 0===h?!1:h;var l=_.jQ(function(m){_.kQ(m,_.$P(null!=f?f:""))});b.print(_.hQ(function(m){m.Ea("OXv8mf");
var p={jscontroller:"WD3M3d",xk:_.EI("VYBDae-Bz112c-LgbsSe","VYBDae-Bz112c-LgbsSe-OWXEXe-ornU0b",g&&"VYBDae-Bz112c-LgbsSe-OWXEXe-IT5dJd",!1),yk:"VYBDae-Bz112c-kBDsod-Rtc0Jf",LF:_.EI("VYBDae-Bz112c-kBDsod-Rtc0Jf","VYBDae-Bz112c-kBDsod-Rtc0Jf-OWXEXe-IT5dJd"),Ch:"VYBDae-Bz112c-UHGRz",bi:"VYBDae-Bz112c-RLmnJb",ariaLabel:"Toggle mute",Na:"tCq9B",disabled:!1,ix:c,bx:d,Bd:g,jsname:"CQj15d",uc:h,fh:!1,attributes:l};m.Ac(E5,"DsOYUd","button",p,a,wta);m.Fa()}))},K5,L5,M5,N5,O5,P5,Q5,R5,S5,T5,U5,V5,W5,X5,Y5,
Z5,Bta=function(a,b){var c=this.j,d=b.zw,e=b.ug;b=b.Iw;var f=_.Yk(D5(d),4),g=_.Yk(D5(d),3);var h=""!==f?"background-color: "+_.DI(f)+";":"background-color: "+_.DI("#ffffff")+";";var l=(0,_.tI)(h);h=""!==g?"color: "+_.DI(g)+";":"color: "+_.DI("#000251")+";";var m=(0,_.tI)(h);h=""!==g?"color: "+_.DI(g)+";":""!==f?"color: "+_.DI("#000251")+";":"";var p=(0,_.tI)(h);h=_.jQ(function(A){""!==_.Yk(d,2)&&A.W("style","background: "+_.DI(_.Yk(d,2))+";")});a.open("header","Zq8nXe");a.va(U5||(U5=["jsaction","rcuQ6b:npT2md",
"class","Qh6GKb"]));a.W("jscontroller","XUkJcc");_.kQ(a,_.$P(h));a.qa();a.Ka("div","kP7Nnb");a.va(V5||(V5=["class","SLH8Ib"]));a.qa();a.Ka("div","hNUm1");a.va(W5||(W5="class rDVoU jsname PmSTRc jsaction click:SW2Y8(Bki2je)".split(" ")));a.qa();_.Uk(_.yD(d,_.w5,3),1)||(h=_.hQ(function(A){A.Ea("Wi1HZd");_.D3(A,"https://fonts.gstatic.com/s/i/googlematerialiconsfilled/home/v16/24px.svg",void 0,"k1iVGd");A.Fa()}),a.Ea("p9jidd"),yta(c,a,h),a.Fa());a.close();a.Ka("div","KlJUuf");a.va(X5||(X5=["class","rDVoU",
"jsaction","JIbuQc: trigger.XfeL3c"]));a.qa();var t=_.Uk(D5(d),1);h=0<D5(d).Qb().trim().length?D5(d).Qb()+": ":"";var u=_.jQ(function(A){A.W("style",_.DI(l)+" "+_.DI(m))}),v=_.jQ(function(A){A.W("alt","Share High Score");var F=_.jQ(function(X){""!==f&&""!==g&&X.W("style","filter: opacity(0.5) drop-shadow(0 0 0 #5fa11e)")});_.kQ(A,_.$P(F))}),z=_.hQ(function(A){t||(A.Ea("H8ag5"),_.D3(A,"https://www.gstatic.com/h5games_gamecenter/images/play-page-share.svg",void 0,"zHGI5b",v),A.Fa())});a.Ea("GLyAJb");
_.u2(c,a,h+e,"JffIUc",t,z,!0,"x1L3k",void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,u);a.Fa();a.close();a.Ka("div","YoG6S");a.va(Y5||(Y5=["class","rDVoU"]));a.qa();a.Ka("div","zNeOvc");a.va(Z5||(Z5=["class","xhUuO","jsaction","JIbuQc:aokBrd"]));a.qa();e=_.jQ(function(A){A.W("style",_.DI(l)+" "+_.DI(p))});h=_.hQ(function(A){var F=_.hQ(function(D){D.Ea("UWtwce");D.open("svg","IQPrnb");D.va(R5||(R5=["enable-background","new 0 0 24 24","focusable","false"]));D.W("height","24");D.W("viewBox",
"0 0 24 24");D.W("width","24");D.W("class"," NMm5M");_.kQ(D,_.$P(""));D.qa();D.Ka("g","XbnDBc");D.qa();D.Ka("rect","vrbMTe");D.va(S5||(S5="fill none height 24 width 24".split(" ")));D.qa();D.close();D.close();D.Ka("g","HsHl8c");D.qa();D.Ka("g","KwbYEc");D.qa();D.Ka("path","a7p0Rd");D.va(T5||(T5=["d","M3,9v6h4l5,5V4L7,9H3z M16.5,12c0-1.77-1.02-3.29-2.5-4.03v8.05C15.48,15.29,16.5,13.77,16.5,12z M14,3.23v2.06 c2.89,0.86,5,3.54,5,6.71s-2.11,5.85-5,6.71v2.06c4.01-0.91,7-4.49,7-8.77S18.01,4.14,14,3.23z"]));
D.qa();D.close();D.close();D.close();D.Ya();D.Fa()}),X=_.jQ(function(D){D.W("alt","Toggle mute")});A.Ea("i3htQd");_.h2(A,F,void 0,X);A.Fa()});u=_.hQ(function(A){var F=_.hQ(function(D){D.Ea("rkJbSe");D.open("svg","R31etc");D.va(L5||(L5=["enable-background","new 0 0 24 24","focusable","false"]));D.W("height","24");D.W("viewBox","0 0 24 24");D.W("width","24");D.W("class"," NMm5M");_.kQ(D,_.$P(""));D.qa();D.Ka("g","OoMQ7");D.qa();D.Ka("rect","YgeP5e");D.va(M5||(M5="fill none height 24 width 24".split(" ")));
D.qa();D.close();D.close();D.Ka("g","D3P8V");D.qa();D.Ka("g","jYmbrf");D.qa();D.Ka("path","chz9pb");D.va(N5||(N5=["d","M16.25,13.42C16.4,12.97,16.5,12.5,16.5,12c0-1.77-1.02-3.29-2.5-4.03v3.2L16.25,13.42z"]));D.qa();D.close();D.Ka("path","VABY1");D.va(O5||(O5=["d","M19,12c0,1.21-0.31,2.34-0.85,3.32l1.46,1.46C20.48,15.39,21,13.76,21,12c0-4.28-2.99-7.86-7-8.77v2.06 C16.89,6.15,19,8.83,19,12z"]));D.qa();D.close();D.Ka("path","WeLqAc");D.va(P5||(P5=["d","M2.81,2.81L1.39,4.22L6.17,9H3v6h4l5,5v-5.17l3.32,3.32c-0.42,0.23-0.85,0.43-1.32,0.56v2.06c1-0.23,1.94-0.62,2.79-1.15 l2.99,2.99l1.41-1.41L2.81,2.81z"]));
D.qa();D.close();D.Ka("polygon","NCbAEd");D.va(Q5||(Q5=["points","12,9.17 12,4 9.41,6.59"]));D.qa();D.close();D.close();D.close();D.Ya();D.Fa()}),X=_.jQ(function(D){D.W("alt","Toggle mute")});A.Ea("GGhEId");_.h2(A,F,void 0,X);A.Fa()});a.Ea("CPIE");Ata(c,a,h,u,!b,e);a.Fa();a.close();a.close();_.Z1&&(a.Ea("QGaMdb"),_.Y3(c,a,!1,"LbSQHe"),a.Fa());a.close();a.Ya()},$5,a6,b6,c6,d6,e6,f6,g6,h6,i6,j6,Cta=function(a){var b=a.sr;a="Think you can beat my score of "+a.ug+" on ";return a=a+b+"? Click to accept my challenge:"},
Dta=function(a,b){var c=this.j,d=this.U,e=b.WD,f=b.sr,g=b.ug;b=b.BE;a.open("section","VUqKtb");a.va($5||($5="class,ccabnd,jsname,q96DZd,jsaction,rcuQ6b:npT2md; click:szJ0Be".split(",")));a.W("jscontroller","eHJLOc");a.qa();a.Ka("div","vEISHc");a.va(a6||(a6=["class","S3alVc"]));a.qa();a.Ka("div","e5rjIe");a.va(b6||(b6=["class","wTzo1d"]));a.qa();a.Ka("img","gTpmSc");a.va(c6||(c6=["class","yB5JUc","alt",""]));a.W("src",_.I1("https://www.gstatic.com/h5games_gamecenter/images/share-left-confetti.svg"));
a.qa();a.close();a.Ka("img","YluWS");a.va(d6||(d6=["class","yB5JUc DtErx"]));a.W("src",_.I1(b));a.W("alt",f);a.qa();a.close();a.Ka("img","gVsrKb");a.va(e6||(e6=["class","yB5JUc","alt",""]));a.W("src",_.I1("https://www.gstatic.com/h5games_gamecenter/images/share-right-confetti.svg"));a.qa();a.close();a.close();a.Ka("h1","hRMjD");a.va(f6||(f6=["class","cHThEb"]));a.qa();a.text("Your Score: ");a.print(_.pQ(g));a.text("!");a.close();a.Ka("h1","Nag1dd");a.va(g6||(g6=["class","uZf13d"]));a.qa();a.text("Invite your friends to beat your score");
a.close();a.Ka("div","ZZzIr");a.va(h6||(h6=["class","gLCWQd","jsname","b4vpge"]));a.qa();a.Ea("CmFDtb");_.k3(a,Cta,{ug:g,sr:f},c);a.Fa();a.text(" ");a.open("a","WSFZB");a.W("href",_.CI(e));a.qa();a.print(e);a.close();a.close();a.Ka("div","RR35Kb");a.va(i6||(i6=["class","Tzgmm","jsaction","JIbuQc:rt6p5b"]));a.qa();a.Ea("bCAyXe");_.u2(c,a,d?"Copied":"Copy message","pJKzod");a.Fa();a.close();a.Ka("div","LezTWd");a.va(j6||(j6=["class","Tzgmm","jsaction","JIbuQc:szJ0Be"]));a.qa();a.Ea("eXOFj");zta(c,a,
d?"Done":"Cancel");a.Fa();a.close();a.close();a.Ya()},k6,l6,m6,n6,o6,p6,q6,r6,s6,t6,u6,v6,w6,x6,Eta=function(a){var b=this.U;a.open("div","rBmUfe");a.va(k6||(k6=["jsaction","rcuQ6b:npT2md;K6volc:vOZPHf;Nz2fRe:TehHBb;QrUNgc:r4MMpf"]));a.W("jscontroller","UMGpGb");a.qa();b&&(a.open("div","aq9wtd"),a.va(l6||(l6=["class","LFp1Qc w7IXRd"])),a.qa(),a.Ka("div","Ty715c"),a.va(m6||(m6=["class","N83MOb"])),a.qa(),a.Ka("div","IYCBve"),a.va(n6||(n6=["class","CzrRpc"])),a.qa(),a.Ka("img","kVsQgd"),a.va(o6||(o6=
["alt","","class","yKAdE cgzekb"])),a.W("src",_.I1("https://gstatic.com/h5games_gamecenter/images/shooting_star.svg")),a.qa(),a.close(),a.Ka("img","kcQ6te"),a.va(p6||(p6=["alt","","class","yKAdE V09YJc"])),a.W("src",_.I1("https://gstatic.com/h5games_gamecenter/images/shooting_star.svg")),a.qa(),a.close(),a.Ka("img","dIduWc"),a.va(q6||(q6=["alt","","class","yKAdE DbRmwb"])),a.W("src",_.I1("https://gstatic.com/h5games_gamecenter/images/shooting_star.svg")),a.qa(),a.close(),a.Ka("img","zFPjvf"),a.va(r6||
(r6=["alt","","class","yKAdE xAF84e"])),a.W("src",_.I1("https://gstatic.com/h5games_gamecenter/images/shooting_star.svg")),a.qa(),a.close(),a.Ka("img","iHjVEc"),a.va(s6||(s6=["alt","","class","yKAdE ftNKne"])),a.W("src",_.I1("https://gstatic.com/h5games_gamecenter/images/shooting_star.svg")),a.qa(),a.close(),a.Ka("img","TcSigd"),a.va(t6||(t6=["alt","","class","yKAdE pIWTDd"])),a.W("src",_.I1("https://gstatic.com/h5games_gamecenter/images/shooting_star.svg")),a.qa(),a.close(),a.Ka("div","AXZ8n"),a.va(u6||
(u6=["class","kxKhub i6vF0d"])),a.qa(),a.Ka("img","OHq51e"),a.va(v6||(v6=["alt","","class","XNNagb"])),a.W("src",_.I1("https://gstatic.com/h5games_gamecenter/images/sammy.svg")),a.qa(),a.close(),a.close(),a.Ka("img","QDt4tb"),a.va(w6||(w6=["alt","","class","QTlUN i6vF0d"])),a.W("src",_.I1("https://gstatic.com/h5games_gamecenter/images/powered_by.svg")),a.qa(),a.close(),a.Ka("img","xinpbd"),a.va(x6||(x6=["alt","Splash screen: Powered by GameSnacks","class","Ks2qOd i6vF0d"])),a.W("src",_.I1("https://gstatic.com/h5games_gamecenter/images/gamesnacks_logo.svg")),
a.qa(),a.close(),a.close(),a.close(),a.close());a.Ya()},y6,z6,A6,B6,C6,Fta=function(a,b,c){var d=(0,_.tI)("left: calc(clamp(16px, 6.5%, 91px) + max(0px, calc((100% - 100rem)/2))); top: 3.5rem;"),e=void 0===b?"":b;b=void 0===c?"":c;d=_.DI(null!=d?d:"");d+=";";c=""!==e?"background-color: "+_.DI(e)+";":"";c=(0,_.tI)(c);d+=_.DI(c);d+=";";b=""!==b?"color: "+_.DI(b)+";":"";b=(0,_.tI)(b);d+=_.DI(b);var f=(0,_.tI)(d+";");d=_.jQ(function(g){g.W("style",_.DI(f))});a.open("a","o7V5Id");a.va(A6||(A6="class,b4a4bd,jsaction,rcuQ6b:rWR8le; click:M66pue,aria-label,Go Home".split(",")));
_.kQ(a,_.$P(d));a.qa();d=_.jQ(function(g){""!==e&&g.W("style","border-bottom-color: "+_.DI(e)+";")});a.Ka("div","sQMzxc");a.va(B6||(B6=["class","b66Gpf"]));_.kQ(a,_.$P(d));a.qa();a.close();a.Ka("div","ucHnrd");a.va(C6||(C6=["class","XU4jUe"]));a.qa();a.text("Play More Games");a.close();a.Ya()},D6,Gta=function(a,b){var c=this.j,d=this.V,e=this.ka,f=this.T,g=this.oa,h=this.ua,l=this.U,m=b.Xb,p=b.Sb;a.open("div","xMDe9d");a.va(D6||(D6=["class","H81QOc","jsaction","rcuQ6b:npT2md;JZCswc:PkMYQd;qBjjw:L7Rt8d;KCJ1zb:mhoHEe"]));
a.W("jscontroller","MNuO1");a.qa();a.Ea("N0DFMd");b=_.yD(_.yD(d,_.HD,1),_.A5,1);a.open("div","ukYnHb");a.va(z6||(z6=["class","UmZ0b"]));a.W("jsaction","QIDTKc:Okwk4;ygDFDd:szJ0Be;"+(_.Uk(D5(b),1)?"":"XfeL3c:QJGVnd")+";");a.qa();_.Uk(b,1)||(a.Ea("vQGL7e"),l={Xb:m,gameId:_.ND(p),zw:b,ug:f,Iw:l},a.Ac(_.x5,"Zq8nXe","header",l,c,Bta),a.Fa());a.Ea("ZXruef");l=p.j().getName();a.open("iframe","cP4sUc");a.va(y6||(y6=["allow","autoplay","jsname","UPVbTb"]));a.W("class","kTZXGd bUHK2b");a.W("title",l);a.qa();
a.Ya();a.Fa();a.Ea("sSAgdf");a.Ac(_.z5,"rBmUfe","div",null,c,Eta);a.Fa();e&&(a.Ea("LI7HTb"),e={WD:g,Xb:m,gameId:_.ND(p),sr:p.j().getName(),ug:f,BE:(0,_.rI)(""+_.j2(p,3))},a.Ac(_.y5,"VUqKtb","section",e,c,Dta),a.Fa());e=""===_.Yk(D5(b),4)?"#000251":_.Yk(D5(b),4);h&&(a.Ea("vltO9c"),Fta(a,e,_.Yk(D5(b),3)),a.Fa());_.Uk(_.yD(d,_.zD,2),1)||(a.Ea("qtbbNb"),_.m3(a,{qj:!1,Cm:_.Yk(_.yD(d,_.zD,2),2)},c),a.Fa());a.Ya();a.Fa();a.Ya()},E6,Hta=function(a,b,c,d,e,f){_.l4(a,b,_.hQ(function(g){var h=null!=e?e:f;if(null==
h)g.Ea("dN7yPc"),g.open("div","helwA"),g.va(K5||(K5=["jsaction","rcuQ6b:QtyCCc"])),g.W("jscontroller","ROMAPc"),g.qa(),g.Ya();else{g.open("h1","vQW1He");g.va(E6||(E6=["style","display: none;"]));g.qa();var l=_.yD(h,_.MD,1);g.print(l.j().getName());g.close();g.Ea("Ocma8b");_.d4(g,l.j().getName(),_.Yk(c,1),_.ND(l));g.Fa();g.Ea("e4grvb");h={Xb:_.Yk(c,1),Sb:l,px:_.yD(h,_.OD,2),GG:_.Uk(c,3)};g.Ac(_.B5,"xMDe9d","div",h,a,Gta)}g.Fa()}),d,c)},F6=function(a,b,c){Hta(c,a,b.Lf,b.Mi,b.Vv,b.Uv)};F6.hc=_.$y;
var G6,H6,I6,J6=function(a,b,c){var d=b.Vv;b=b.Uv;c=c.lv;d=null!=d?d:b;var e;if(null==d?0:null==(e=_.Mk(d,_.MD,1))?0:e.Wd())e="Play "+_.Mk(d,_.MD,1).Wd().getName()+" on GameSnacks, a bite-sized online gaming site you can play on your phone and desktop without installing anything.",a.open("meta","zHlGob"),a.va(G6||(G6=["name","description"])),a.W("content",e),a.qa(),a.close(),a.Ka("meta","JeNpXc"),a.va(H6||(H6=["property","og:description"])),a.W("content",e),a.qa(),a.close(),a.Ka("link","E8pDG"),a.va(I6||
(I6=["rel","canonical"])),a.W("href","https://"+c+"/games/"+_.ND(_.Mk(d,_.MD,1))),a.qa(),a.close(),a.Ka("title","GKBtCe"),a.qa(),a.text("Play Bite-Sized "),a.text(String(_.Mk(d,_.MD,1).Wd().getName())),a.text(" Online Now - GameSnacks"),a.close()};J6.hc=_.$y;var K6=function(a){_.hB.call(this,a.na)};_.H(K6,_.hB);K6.ha=_.hB.ha;_.k=K6.prototype;_.k.Cr=function(){return"EtQCnc"};_.k.Cp=function(){return!0};_.k.Ir=function(){return F6};_.k.Ll=function(){return J6};_.k.dw=function(){return!0};
_.fB(_.kE,K6);_.rA.EtQCnc=_.pE;

_.r();
}catch(e){_._DumpException(e)}
}).call(this,this.default_GameCenterUi);
// Google Inc.
